### ISSUE TITLE
Should provide a list of Departments

### ISSUE THREAD

**Issue by Daimonos** [Daimonos/LessonsLearned#3]
An administrator should be able to define which departments are available and make the user choose from the list of when proposing a new lesson

**Comment by Daimonos** [comment]
Added administrative capabilities

**Comment by WenInCode** [comment]
Updated submission form to load departments and list them in select.

**Comment by WenInCode** [comment]
Updated the search to properly query for departments. Previously was using `$scope.department._id` in the query, but lessons (as of right now) only store departments & disciplines as strings. Therefore the search query should use `$scope.department.name` instead. This is not as efficient when it comes to searching as it has to match a full-text, we could just add the actual schemas to the lessons and search by ID. 

Opinion?

**Comment by Daimonos** [comment]
I believe that this has all been taken care of to date. Closing
